packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  msgpackr-extract: true
  prisma: true

overrides:
  postcss: ">=8.5.12"
  glob: ">=10.5.0"
