.PHONY: build test fmt clean

build:
	cargo build --target wasm32-unknown-unknown --release

build-v1:
	cargo build --target wasm32v1-none --release

test:
	cargo test

fmt:
	cargo fmt

clean:
	cargo clean
